common: &common
  adapter: postgresql
  encoding: unicode
  
production:
  <<: *common
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  database: my_app
  pool: 5

